apiVersion: apps/v1
kind: Deployment
metadata:
  name: github-insights-pro
  namespace: github-insights-pro
  labels:
    app: github-insights-pro
spec:
  replicas: 2
  selector:
    matchLabels:
      app: github-insights-pro
  template:
    metadata:
      labels:
        app: github-insights-pro
    spec:
      containers:
      - name: github-insights-pro
        image: github-insights-pro:latest
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: github-insights-pro-config
              key: NODE_ENV
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: github-insights-pro-config
              key: PORT
        - name: NEXT_PUBLIC_GITHUB_TOKEN
          valueFrom:
            secretKeyRef:
              name: github-insights-pro-secrets
              key: NEXT_PUBLIC_GITHUB_TOKEN
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
